documentary_wire_homepage:
    pattern:  /
    defaults: { _controller: BaseBundle:Home:index }

documentary_wire_home:
    pattern: /home/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_homepage
        permanent: true # this is for 301

documentary_wire_index:
    pattern: /index.php/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_homepage
        permanent: true # this is for 301

documentary_wire_index:
    pattern: /index.html/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_homepage
        permanent: true # this is for 301

documentary_wire.sitemap:
    pattern:  /sitemap.xml
    defaults: { _controller: BaseBundle:Site:sitemap }

documentary_wire.sitemap_documentary:
    pattern:  /sitemap-documentary.xml
    defaults: { _controller: BaseBundle:Site:sitemapDocumentary }

documentary_wire.sitemap_category:
    pattern:  /sitemap-category.xml
    defaults: { _controller: BaseBundle:Site:sitemapCategory }

documentary_wire.sitemap_page:
    pattern:  /sitemap-page.xml
    defaults: { _controller: BaseBundle:Site:sitemapPage }

documentary_wire.search:
    pattern:  /search/
    defaults: { _controller: BaseBundle:Search:search }

documentary_wire.show_tag:
    pattern: /tag/{slug}/
    defaults: { _controller: CategoryBundle:Tag:showTag }

documentary_wire_browse:
    pattern: /browse/
    defaults: { _controller: DocumentaryBundle:Documentary:browse, page: 1 }

documentary_wire_browse_first:
    pattern: /browse/page/1/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_browse
        permanent: true # this is for 301

documentary_wire_browse_page:
    pattern: /browse/page/{page}/
    defaults: { _controller: DocumentaryWIREBundle:Documentary:browse, page: page }

documentary_wire_all:
    pattern: /all/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_browse
        permanent: true # this is for 301

documentary_wire_all_page:
    pattern: /all/page/{page}/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: documentary_wire_browse_page
        permanent: true # this is for 301

documentary_wire.list:
    pattern: /watch-online/
    defaults: { _controller: DocumentaryBundle:Documentary:list }

documentary_wire_like_documentary:
    pattern: /ajax/like/documentary
    defaults: { _controller: LikeBundle:Like:like }
    requirements:
        _method: POST

documentary_wire_ajax_follow_user:
    pattern: /ajax/follow/user
    defaults: { _controller: FollowBundle:Follow:ajaxFollow }

documentary_wire_follow_user:
    pattern: /follow/{username}
    defaults: { _controller: FollowBundle:Follow:follow }

#documentary_wire.admin_show_dashboard:
 #   pattern: /admin/dashboard
  #  defaults: { _controller: DocumentaryWIREBundle:Admin:showDashboard }

#documentary_wire.admin_create_documentary:
 #   pattern: /admin/documentary/create
  #  defaults: { _controller: DocumentaryWIREBundle:Admin:createDocumentary }

#documentary_wire.admin_show_documentary:
#    pattern: /admin/documentary/show/{slug}/
#    defaults: { _controller: DocumentaryWIREBundle:Admin:showDocumentary }

#documentary_wire.migrate_from_wordpress:
#    pattern: /admin/migrate
#    defaults: { _controller: DocumentaryWIREBundle:Admin:migrateFromWordpress }


documentary_wire.rss_feed:
    pattern: /feed/
    defaults: { _controller: BaseBundle:Feed:siteFeed }

documentary_wire.category_rss_feed:
    pattern: /category/{slug}/feed/
    defaults: { _controller: BaseBundle:Feed:categoryFeed }

documentary_wire.contact:
    pattern: /contact/
    defaults: { _controller: BaseBundle:Site:contact }

documentary_wire.show_wp_login:
    pattern: /wp-login.php/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: login
        permanent: true # this is for 301

document